# Generated by Django 3.2.14 on 2022-11-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='criminalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crim_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('height', models.FloatField(blank=True, null=True)),
                ('eyes', models.CharField(max_length=20)),
                ('skin', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('refer', models.ImageField(upload_to='media/')),
                ('org', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
