# Generated by Django 3.2.14 on 2022-11-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRapp', '0002_criminalmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalmodel',
            name='lat',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criminalmodel',
            name='longt',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
